Header
vrd096/nerds pull request #1
Opened 2019-04-19 08:05 UTC by vrd096

2019-04-19 12:59 UTC, ghost requested changes

2019-04-19 12:59 UTC, ivan-academy commented on style.css
> +    font-size: 16px;
для чего тебе `font-size` здесь?

2019-04-19 12:59 UTC, ivan-academy commented on style.css
> +a{
страдает форматирование кода

2019-04-19 12:59 UTC, ivan-academy commented on index.html
> +             <a href="/" class="nav__logo">
1. `nav__logo` если это BEM то почему все остальное не BEM?
2. почему элемент находится за пределами компонента? `nav__log` class не может быть использован за пределами `nav` класса..

2019-04-19 12:59 UTC, ivan-academy commented on index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
это нам навредит.. т.к. у нас не адаптивный сайт.. он будет криво отображаться на маленьком экране с этой инструкцией

2019-04-19 12:59 UTC, ivan-academy commented on index.html
> +        <div class="wrapper">
wrapper это как то слишком унивирсально.. ты ведь только здесь его используешь.. а что если тебе другой warpper понадобиться в другой секции как ты его тогда назовешь?

2019-04-19 12:59 UTC, ivan-academy commented on style.css
> +     border-bottom: 2px solid #fb565a;
зачем там пустая строка?

2019-04-19 13:04 UTC, ivan-academy commented
Внимательно посмотри видео с skype сессии где я размечал, там четко прослеживается как я делал BEM структуру. Также нужно настроить форматирование, чтобы просто alt-shift-f делало все красиво.. иначе код сложно читать.

2019-04-19 13:05 UTC, vrd096 commented on style.css
> +    font-size: 16px;
потому что основной текст в макете 16px

2019-04-19 13:18 UTC, vrd096 commented on style.css
> +a{
поясни что именно? не понимаю

2019-04-19 13:22 UTC, vrd096 commented on index.html
> +        <div class="wrapper">
я использую wrapper универсально, потому что в нем настройки сетки ) я во всех секциях оберну в обертку, чтобы все стояло по сетке, если нужны будут доп стили, я просто добавлю ему еще один класс

2019-04-19 13:48 UTC, vrd096 commented
https://codesandbox.io/s/j3rnj6935w

2019-04-19 14:26 UTC, ivan-academy commented on index.html
> +              <a href="/about" class="nav__link is-active">Студия</a>
Пусть у тебя первым атрибутом будет всегда `class`, если он есть. Так проще будет в будущем.

2019-04-19 14:27 UTC, ivan-academy commented on index.html
> +          <ul class="nav__links-list">
Давай вместо `nav__links-list` и `nav__links-item` просто напишем:
`nav__list`
`nav__item`

2019-04-19 14:28 UTC, ivan-academy commented on index.html
> +          />
Опить же лучше первым атрибутом делать `class`

2019-04-19 14:30 UTC, vrd096 commented on index.html
> +              <a href="/about" class="nav__link is-active">Студия</a>
я не пишу в ручную, я пишу тег.названиекласса и потом таб

2019-04-19 14:32 UTC, ivan-academy commented on style.css
> +}
Давай мы разделим твой wrapper на два класса:
- класс `container` который будет универсальный и только будет задавать `max-width` и `margin: 0 auto`
- класс `header__inner` - который специфичен только для header компонента

2019-04-19 14:34 UTC, ivan-academy commented on style.css
> +}
`cart` пусть будет идти после `.nav__link-icon` а не между ними, т.к. элементы одного компонента коде должны идти вместе

2019-04-19 16:34 UTC, ivan-academy commented
Закончи эти изменения и можешь моржить.

2019-04-20 06:26 UTC, ivanvotti commented on index.html
> +        <div class="header__inner">
Тебе не нужно здесь два вложенных `div`. Просто один `div` с двумя классами через пробел. `header__inner wrapper`

2019-04-20 06:28 UTC, ivan-academy commented on index.html
> +        <div class="header__inner">
Тебе не нужно здесь два вложенных div. Просто один div с двумя классами через пробел. header__inner wrapper

2019-04-20 09:00 UTC, merged