Footer
vrd096/nerds pull request #5
Opened 2019-05-05 14:56 UTC by vrd096

https://codesandbox.io/s/my7wzkq2xj

2019-05-06 18:21 UTC, ghost requested changes
Карточка над картой с адресом не верно позиционируется, если сравнивать с макетом.

2019-05-06 18:21 UTC, ivan-academy commented on index.html
> +            <span class="social__discount--slogan">
Как думаешь в чем здесь ошибка?

2019-05-06 18:21 UTC, ivan-academy commented on index.html
> +      <section class="contacts">
Ты не забыл что у каждой секции должен быть ...

2019-05-06 18:21 UTC, ivan-academy commented on index.html
> +            </p>
Как только делаешь два <br> подряд задай себе вопрос, а как это сделать адекватнее. Например так:
```html
<p class="contacts__text">
  191186, Санкт-Петербург,
  <br />
  ул. Б. Конюшенная, д. 19/8
</p>
<p class="contacts__text">
  тел. +7 (812) 275-75-75
</p>
```

2019-05-08 06:10 UTC, vrd096 commented on index.html
> +      <section class="contacts">
main?

2019-05-08 08:29 UTC, ivan-academy commented
:shipit:

2019-05-08 08:43 UTC, merged